import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { SolanaProvider } from "@/components/providers/walletProvider";
import { Toaster } from "sonner";

const geistSans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.className} antialiased bg-background text-foreground`}
      >
        <Toaster />
        <SolanaProvider>
          {children}
        </SolanaProvider>
      </body>
    </html>
  );
}
